blank_issues_enabled: true  # trueë¡œ ì„¤ì •í•˜ì—¬ ë¹ˆ ì´ìŠˆë„ í—ˆìš©
contact_links:
  - name: ğŸŒ± 9crops Discussions
    url: https://github.com/prgrms-web-devcourse-final-project/WEB2_3_9crops_BE/discussions
    about: template
